<!--

    Copyright © 2016-2025 The Thingsboard Authors

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.thingsboard</groupId>
        <version>4.2.1.1</version>
        <artifactId>thingsboard</artifactId>
    </parent>
    <groupId>org.thingsboard</groupId>
    <artifactId>ui-ngx</artifactId>
    <packaging>jar</packaging>

    <name>ThingsBoard Server UI</name>
    <url>https://thingsboard.io</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <main.dir>${basedir}/..</main.dir>
        <skip.ui>false</skip.ui>
    </properties>

    <build>
        <resources>
            <resource>
                <directory>${project.build.directory}/generated-resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>yarn install</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <skip>${skip.ui}</skip>
                            <executable>yarn</executable>
                            <arguments>
                                <argument>install</argument>
                                <argument>--non-interactive</argument>
                                <argument>--network-concurrency</argument>
                                <argument>4</argument>
                                <argument>--network-timeout</argument>
                                <argument>100000</argument>
                                <argument>--mutex</argument>
                                <argument>network</argument>
                            </arguments>
                            <workingDirectory>${basedir}</workingDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>yarn build</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <skip>${skip.ui}</skip>
                            <executable>yarn</executable>
                            <arguments>
                                <argument>run</argument>
                                <argument>build:prod</argument>
                            </arguments>
                            <workingDirectory>${basedir}</workingDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>yarn-start</id>
            <activation>
                <property>
                    <name>yarn-start</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>yarn start</id>
                                <phase>process-resources</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>yarn</executable>
                                    <arguments>
                                        <argument>start</argument>
                                    </arguments>
                                    <workingDirectory>${basedir}</workingDirectory>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>