/**
 * Copyright © 2016-2025 The Thingsboard Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.server.service.security.auth.iotbridge;

import io.jsonwebtoken.Claims;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;
import org.thingsboard.common.util.JacksonUtil;
import org.thingsboard.server.common.data.Tenant;
import org.thingsboard.server.common.data.User;
import org.thingsboard.server.common.data.exception.ThingsboardErrorCode;
import org.thingsboard.server.common.data.exception.ThingsboardException;
import org.thingsboard.server.common.data.id.TenantId;
import org.thingsboard.server.common.data.security.Authority;
import org.thingsboard.server.common.data.security.UserCredentials;
import org.thingsboard.server.dao.tenant.TenantService;
import org.thingsboard.server.dao.user.UserService;
import org.thingsboard.server.queue.util.TbCoreComponent;

import java.util.Map;
import java.util.UUID;

/**
 * Idempotent provisioning of IoT platform tenant-admin accounts from a verified water-platform assertion.
 * <p>
 * One water-platform user => one tenant (title = original water login name) + one tenant admin (login/email =
 * deterministic email generated by the water platform, carried in the assertion as {@code profile.login}).
 * Repeated or concurrent invocations for the same user return the same account (CREATED / ALREADY_EXISTS).
 */
@Service
@TbCoreComponent
@Slf4j
@RequiredArgsConstructor
public class IoTProvisionService {

    public static final String WATER_USER_ID = "waterUserId";
    public static final String WATER_ORG_ID = "waterOrgId";
    public static final String WATER_AREA_ID = "waterAreaId";

    private final TenantService tenantService;
    private final UserService userService;
    private final BCryptPasswordEncoder passwordEncoder;

    /**
     * Ensures the tenant and the tenant-admin account exist for the given verified assertion.
     *
     * @return provisioning result with the account and the created flag
     */
    public synchronized ProvisionResult ensureAccount(Claims claims) throws ThingsboardException {
        String waterUserId = claims.getSubject();
        String login = readClaim(claims, "login");
        String userName = readClaim(claims, "userName");
        String nickName = readClaim(claims, "firstName");
        String jobNumber = readClaim(claims, "jobNumber");

        if (waterUserId == null || waterUserId.isBlank()) {
            throw new ThingsboardException("Assertion subject (water user id) is missing", ThingsboardErrorCode.BAD_REQUEST_PARAMS);
        }
        if (login == null || !login.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {
            throw new ThingsboardException("Assertion profile.login is missing or invalid", ThingsboardErrorCode.BAD_REQUEST_PARAMS);
        }
        if (userName == null || userName.isBlank()) {
            throw new ThingsboardException("Assertion profile.userName is missing", ThingsboardErrorCode.BAD_REQUEST_PARAMS);
        }

        // 1. Idempotency lookup by the deterministic account login (email). TB user email is unique platform-wide.
        User existing = userService.findUserByEmail(TenantId.SYS_TENANT_ID, login.toLowerCase());
        if (existing != null) {
            Tenant tenant = existing.getTenantId() != null ? tenantService.findTenantById(existing.getTenantId()) : null;
            if (tenant == null) {
                throw new ThingsboardException("User found but tenant is missing", ThingsboardErrorCode.GENERAL);
            }
            // Guard: account must belong to the same water user mapping
            String mapped = tenant.getAdditionalInfo() != null && tenant.getAdditionalInfo().has(WATER_USER_ID)
                    ? tenant.getAdditionalInfo().get(WATER_USER_ID).asText() : null;
            if (mapped != null && !mapped.equals(waterUserId)) {
                log.warn("IoT bridge account [{}] already belongs to water user [{}], requested by [{}]", login, mapped, waterUserId);
                throw new ThingsboardException("Account already exists and belongs to another user", ThingsboardErrorCode.BAD_REQUEST_PARAMS);
            }
            return new ProvisionResult(existing, tenant, false);
        }

        // 2. Tenant lookup by title (water original login name). Login name is unique in the water platform,
        //    therefore the tenant title is unique too; the waterUserId mapping is stored for traceability.
        Tenant tenant = tenantService.findTenantByName(userName);
        if (tenant == null) {
            tenant = new Tenant();
            tenant.setTitle(userName);
            tenant.setAdditionalInfo(JacksonUtil.newObjectNode().put(WATER_USER_ID, waterUserId));
            tenant = tenantService.saveTenant(tenant);
            log.info("IoT bridge created tenant [{}] for water user [{}]", tenant.getTitle(), waterUserId);
        } else {
            // enrich existing tenant with the water user mapping if absent (backward compatibility with manual tenants)
            if (tenant.getAdditionalInfo() == null || !tenant.getAdditionalInfo().has(WATER_USER_ID)) {
                tenant.setAdditionalInfo(JacksonUtil.newObjectNode().put(WATER_USER_ID, waterUserId));
                tenant = tenantService.saveTenant(tenant);
            }
        }

        // 3. Create the tenant admin account (credentials are created disabled by saveUser; activate below)
        User user = new User();
        user.setTenantId(tenant.getId());
        user.setAuthority(Authority.TENANT_ADMIN);
        user.setEmail(login.toLowerCase());
        user.setFirstName(nickName);
        var additionalInfo = JacksonUtil.newObjectNode();
        additionalInfo.put(WATER_USER_ID, waterUserId);
        putIfPresent(additionalInfo, "jobNumber", jobNumber);
        putIfPresent(additionalInfo, WATER_ORG_ID, readClaim(claims, WATER_ORG_ID));
        putIfPresent(additionalInfo, WATER_AREA_ID, readClaim(claims, WATER_AREA_ID));
        user.setAdditionalInfo(additionalInfo);
        user = userService.saveUser(tenant.getId(), user);

        // Activate credentials with a strong random password (password login is not used; access is via the jump exchange)
        try {
            UserCredentials credentials = userService.findUserCredentialsByUserId(tenant.getId(), user.getId());
            String rawPassword = UUID.randomUUID().toString().replace("-", "") + "Aa1!";
            userService.activateUserCredentials(tenant.getId(), credentials.getActivateToken(), passwordEncoder.encode(rawPassword));
        } catch (Exception e) {
            log.warn("IoT bridge failed to activate credentials for user [{}]: {}", login, e.getMessage());
        }
        log.info("IoT bridge created tenant admin [{}] under tenant [{}]", login, tenant.getTitle());
        return new ProvisionResult(user, tenant, true);
    }

    private static void putIfPresent(com.fasterxml.jackson.databind.node.ObjectNode node, String field, String value) {
        if (value != null && !value.isBlank()) {
            node.put(field, value);
        }
    }

    @SuppressWarnings("unchecked")
    private static String readClaim(Claims claims, String field) {
        Object profileObj = claims.get("profile");
        if (profileObj instanceof Map) {
            Object value = ((Map<String, Object>) profileObj).get(field);
            if (value != null) {
                return String.valueOf(value);
            }
        }
        Object value = claims.get("profile." + field);
        return value != null ? String.valueOf(value) : null;
    }

    public record ProvisionResult(User user, Tenant tenant, boolean created) {
    }

}
